import Image from "next/image";
import { CheckCircle2 } from "lucide-react";

const features = [
  "Store all client information in one place",
  "Track invoice history for every client",
  "Manage contact details and business records",
  "View revenue generated by each client",
];

export default function ClientManagementSection() {
  return (
    <section className="relative overflow-hidden px-3 py-12 sm:px-6 sm:py-14 lg:px-8 lg:py-16">
      {/* BACKGROUND */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute right-0 top-1/3 h-64 w-64 rounded-full bg-violet-500/6 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-7xl">
        <div className="grid items-center gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:gap-12">
          {/* LEFT - SCREENSHOT */}
          <div className="relative">
            <div className="absolute inset-0 rounded-[32px] bg-violet-500/10 blur-3xl" />

            <div className="relative overflow-hidden rounded-[32px] border border-white/10 bg-[#0B1120] shadow-[0_25px_80px_rgba(0,0,0,0.4)]">
              <Image
                src="/images/showcase/client-management.png"
                alt="Finvia Client Management"
                width={1400}
                height={900}
                className="h-auto w-full"
              />
            </div>
          </div>

          {/* RIGHT - CONTENT */}
          <div>
            <span className="inline-flex items-center rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs font-medium uppercase tracking-[0.18em] text-violet-400">
              Client Management
            </span>

            <h2 className="mt-4 text-2xl font-semibold tracking-tight text-white sm:text-3xl lg:text-4xl">
              Know your clients
              <br />
              better than ever
            </h2>

            <p className="mt-4 max-w-lg text-sm leading-relaxed text-slate-400 sm:text-base">
              Keep client records, contact information, invoice history, and
              business relationships organized from one centralized workspace.
            </p>

            <div className="mt-8 space-y-4">
              {features.map((feature) => (
                <div key={feature} className="flex items-start gap-3">
                  <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500/10">
                    <CheckCircle2 className="size-4 text-emerald-400" />
                  </div>

                  <p className="pt-0.5 text-sm leading-relaxed text-slate-300 sm:text-base">
                    {feature}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}